### ISSUE TITLE
小米市场在做monkey测试中，崩溃信息

### ISSUE THREAD

**Issue by kala888** [jpush/janalytics-react-native#25]
看起来是cn.jpush.reactnativejanalytics.JAnalyticsModule.postEvent(JAnalyticsModule.java:80)
的问题

```
03-15 16:33:07.091 12395 12463 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
03-15 16:33:07.091 12395 12463 E AndroidRuntime: Process: cn.toaid, PID: 12395
03-15 16:33:07.091 12395 12463 E AndroidRuntime: com.facebook.react.bridge.NoSuchKeyException: couldn't find key name in dynamic object
03-15 16:33:07.091 12395 12463 E AndroidRuntime: at com.facebook.react.bridge.ReadableNativeMap.getString(Native Method)
03-15 16:33:07.091 12395 12463 E AndroidRuntime: at cn.jpush.reactnativejanalytics.JAnalyticsModule.postEvent(JAnalyticsModule.java:80)
03-15 16:33:07.091 12395 12463 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
03-15 16:33:07.091 12395 12463 E AndroidRuntime: at java.lang.reflect.Method.invoke(Method.java:372)
03-15 16:33:07.091 12395 12463 E AndroidRuntime: at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
03-15 16:33:07.091 12395 12463 E AndroidRuntime: at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
03-15 16:33:07.091 12395 12463 E AndroidRuntime: at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-15 16:33:07.091 12395 12463 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:739)
03-15 16:33:07.091 12395 12463 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:95)
03-15 16:33:07.091 12395 12463 E AndroidRuntime: at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-15 16:33:07.091 12395 12463 E AndroidRuntime: at android.os.Looper.loop(Looper.java:135)
03-15 16:33:07.091 12395 12463 E AndroidRuntime: at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
03-15 16:33:07.091 12395 12463 E AndroidRuntime: at java.lang.Thread.run(Thread.java:818)
```

**Comment by JoshLipan** [comment]
更新最新版本再试
