### ISSUE TITLE
关于集成统计功能，用户使用报错日志上传，目前不知道错误在什么地方

### ISSUE THREAD

**Issue by quietautumn** [jpush/janalytics-react-native#29]
应用平台：
  Environment:
    OS: macOS High Sierra 10.13.6
    Node: 8.11.3
    Yarn: 1.9.4
    npm: 5.6.0
    Watchman: Not Found
    Xcode: Not Found
    Android Studio: 3.1 AI-173.4720617

  Packages: (wanted => installed)
    react: 16.3.1 => 16.3.1
    react-native: 0.55.4 => 0.55.4

版本信息：

    "janalytics-react-native": "^1.1.4",
    "jcore-react-native": "^1.2.9",

错误原因：
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
	at cn.jiguang.analytics.android.a.i.b(Unknown Source)
	at cn.jiguang.analytics.android.api.JAnalyticsInterface.onPageEnd(Unknown Source)
	at cn.jpush.reactnativejanalytics.JAnalyticsModule.stopLogPageView(JAnalyticsModule.java:129)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:154)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:761)

出现机型：

![ee2153b8-73da-41e3-8eb1-9e17ea0854a5](https://user-images.githubusercontent.com/16301518/44654276-b4e0aa80-aa23-11e8-8fa6-d6486d10c89b.png)

**Comment by JoshLipan** [comment]
你是在什么地方调用的stopLogPageView

**Comment by quietautumn** [comment]
@JoshLipan ,很多个页面都调用了，但是不能定位是哪个页面出现的问题

**Comment by quietautumn** [comment]
@JoshLipan 
这是简单的封装了一下公共部分
![dc9c8dcc-2a68-4a65-bcee-4ee2410124fc](https://user-images.githubusercontent.com/16301518/44695523-282b0080-aaa6-11e8-8d52-ddeb7ee84669.png)
这是每个页面的调用方法：
![e12b7e1e-98cf-4131-b907-82fd7bd7c047](https://user-images.githubusercontent.com/16301518/44695577-77713100-aaa6-11e8-8bab-2a91b711a813.png)
还有一个错误是startLogPageView的时候报的错，但是出错频率比stopLogPageView会低一些

**Comment by JoshLipan** [comment]
更新插件到v1.1.5

**Comment by quietautumn** [comment]
我先更新之后测试一下再关issue哈
